#!/usr/bin/env bash
# Clean Android build artifacts.
#
# Examples:
#   scripts/clean-android.sh           # gradle clean + remove build outputs
#   scripts/clean-android.sh --deep    # also wipe .gradle caches and copied web assets

set -euo pipefail

DEEP=0

usage() {
  cat <<'EOF'
Usage: scripts/clean-android.sh [--deep]

Removes:
  android/app/build/
  build/android/
  android/capacitor-cordova-android-plugins/ (regenerated by cap sync)

With --deep, also removes:
  android/.gradle/
  android/app/src/main/assets/public/         (synced web bundle)
  android/app/src/main/assets/capacitor.*.json
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --deep) DEEP=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 2 ;;
  esac
done

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if [[ -x android/gradlew ]]; then
  echo "==> gradle clean"
  (cd android && ./gradlew clean || echo "warn: gradle clean failed; falling back to rm -rf")
fi

echo "==> Removing build outputs"
rm -rf android/app/build
rm -rf android/build
rm -rf android/capacitor-cordova-android-plugins
rm -rf build/android

if [[ "$DEEP" -eq 1 ]]; then
  echo "==> Deep clean: gradle cache + synced web assets"
  rm -rf android/.gradle
  rm -rf android/app/src/main/assets/public
  rm -f  android/app/src/main/assets/capacitor.config.json
  rm -f  android/app/src/main/assets/capacitor.plugins.json
fi

echo "Android clean complete."
